Add finalize callback
NWChemEx/ParallelZone pull request #128
Opened 2024-01-18 18:40 UTC by yzhang-23

**PR Type**

- [ ] Breaking change
- [ ] Feature
- [X] Patch

**Brief Description**
Callback function parameters are added into the RuntimeView class to finalize the parallel environment. This is to provide a uniform API for the downstream repos to manage the parallel environment.

**Not In Scope**

**PR Checklist**

- [ ] [Is documented](https://nwchemex.github.io/.github/documenting/index.html)
- [X] [In testing](https://nwchemex.github.io/.github/testing/index.html)
- [ ] [Adheres to applicable organization standards](https://nwchemex.github.io/.github/conventions/index.html)

**TODOs**

- [X] Test RuntimeView in downstream repos.

2024-01-18 20:11 UTC, yzhang-23 commented
Just fixed a ctest error. Will add more stuff into this PR. Not at the stage of merging at this time.

2024-01-18 22:23 UTC, ryanmrichard requested changes
I'm not going to push it, but there really should be more documentation. In particular we should extend the design of the `RuntimeView` to explain why we added callbacks and what we considered in making the decision. Also, since this amounts to a new feature we should also add a tutorial.

2024-01-18 22:23 UTC, ryanmrichard commented on include/parallelzone/runtime/runtime_view.hpp
> +     *  upone the destruction of *this.
```suggestion
     *  upon the destruction of *this. N.b., the functions are called LIFO.
```

2024-01-18 22:23 UTC, ryanmrichard commented on include/parallelzone/runtime/runtime_view.hpp
> +     *  @param[in] cb_func The callback function to add to the stack
```suggestion
     *  @param[in] cb_func The callback function to add to the stack. Assumed to have
     *                     the signature `void ()`.
```

2024-01-18 22:23 UTC, ryanmrichard commented on include/parallelzone/runtime/runtime_view.hpp
> +     *  @throw None No throw guarantee.
```suggestion
     *  @throw std::bad_alloc if there is problem adding the function
     *                        to the stack. Strong throw guarantee.
```
I'm assuming it's strong throw. Does it also throw if there's no PIMPL?

2024-01-18 22:23 UTC, ryanmrichard commented on src/parallelzone/runtime/detail_/runtime_view_pimpl.hpp
> +     *  @throw None No throw guarantee.
Needs updated.

2024-01-18 22:23 UTC, ryanmrichard commented on src/parallelzone/runtime/detail_/runtime_view_pimpl.hpp
> +    std::stack<std::function<void()>> m_callbacks_final;
```suggestion
    std::stack<callback_function_type> m_callbacks_final;
```

2024-01-18 22:23 UTC, ryanmrichard commented on src/parallelzone/runtime/detail_/runtime_view_pimpl.ipp
> +    m_callbacks_final.push(cb_func);
```suggestion
    m_callbacks_final.push(std::move(cb_func));
```
Just in case they have state (like a lambda or a functor).

2024-01-18 22:23 UTC, ryanmrichard commented on src/parallelzone/runtime/detail_/runtime_view_pimpl.ipp
> +        stack_callback(std::function<void()>{&mpi_finalize_wrapper});
```suggestion
        stack_callback(callback_function_type{&mpi_finalize_wrapper});
```

2024-01-18 22:23 UTC, ryanmrichard commented on src/parallelzone/runtime/runtime_view.cpp
> +    pimpl_().stack_callback(cb_func);
```suggestion
    pimpl_().stack_callback(std::move(cb_func));
```

2024-01-18 22:23 UTC, ryanmrichard commented on tests/cxx/unit_tests/parallelzone/runtime/detail_/runtime_view_pimpl.cpp
> +
I'd recommend testing for stack behavior, i.e., push back two lambdas and have the first ensure that the second one was called first.

2024-01-18 22:23 UTC, ryanmrichard commented on tests/python/unit_tests/runtime/test_runtime_view.py
> +        def turn_off(val=is_running):
test here for stack behavior too.

2024-01-22 16:11 UTC, ryanmrichard commented on src/parallelzone/runtime/detail_/runtime_view_pimpl.hpp
> +    std::stack<callback_function_type> m_callbacks_final;
```suggestion
    std::stack<callback_function_type> m_callbacks_final_;
```
This is a private member so it should end in an underscore. You're going to have to work the new name through the file.

2024-01-22 16:36 UTC, ryanmrichard approved these changes

2024-01-22 16:41 UTC, jwaldrop107 approved these changes
LGTM

2024-01-22 16:41 UTC, merged

2024-01-22 16:41 UTC, ryanmrichard commented
🚀 [[bumpr]](https://github.com/haya14busa/action-bumpr) [Bumped!](https://github.com/NWChemEx/ParallelZone/actions/runs/7614439005) **New version**:[v0.1.21](https://github.com/NWChemEx/ParallelZone/releases/tag/v0.1.21) **Changes**:[v0.1.20...v0.1.21](https://github.com/NWChemEx/ParallelZone/compare/v0.1.20...v0.1.21)